name: Cypress Run CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      
      - name: Install Dependencies
        run: npm install

      - name: Set up ServerRest
        run: npm start &

      - name: Wait ServerRest
        run: |
          until nc -z localhost 3000; do
          sleep 1
          done
      
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          config-file: ./cypress.config.ts
          browser: chrome
          headless: true
          spec: cypress/e2e/**/*.cy.js

      - name: Upload test failures
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos