name: Cypress Run CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Setup ServerRest
        run: npm start &

      - name: Wait ServerRest
        run: |
          until nc -z localhost 3000; do
          sleep 1
          done
      
      - name: Run Tests
        run: npm run cy:open